apiVersion: v2
publisher: ms-toolsai
name: jupyter
version: latest
type: VS Code extension
displayName: Jupyter
title: Jupyter
description: 'Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.'
icon: /images/ms-toolsai-jupyter-icon.png
category: Programming Languages
repository: 'https://github.com/Microsoft/vscode-jupyter'
firstPublicationDate: '2022-02-01'
latestUpdateDate: '2022-02-10'
spec:
  containers:
    - image: 'registry.redhat.io/codeready-workspaces/plugin-java8-rhel8:2.14'
      name: vscode-jupiter
      volumes:
        - name: venv
          mountPath: /home/jboss/.venv
      memoryLimit: 1Gi
      memoryRequest: 20Mi
      cpuRequest: 30m
      cpuLimit: 500m
  extensions:
    - 'relative:extension/resources/open-vsx_org/api/ms-toolsai/jupyter/2022_1_1001781940/file/ms-toolsai.jupyter-2022.1.1001781940.vsix'
